keys:
  - &primary age1u0h8j45ym4jqffhc6jlr8metcl4czylv7ct7ngusrxrklnfsgvmsd8qzvs
  - &lily age1r520ahjdksrj7wpfjn9jv75sdcceyhlqzwpvhrhq30k78dj4wpasnulrzh
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
          - *lily
