#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Script to take screenshots with grim, slurp (in Wayland)

# Get Colors
DIR="$HOME/.config/niri"
background="$(cat "$DIR"/rofi/shared/colors.rasi | grep 'background:' | cut -d':' -f2 | tr -d ' '\;)"
accent="$(cat "$DIR"/rofi/shared/colors.rasi | grep 'selected:' | cut -d':' -f2 | tr -d ' '\;)"

iDIR="$HOME/.config/niri/mako/icons"

time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$HOME/Pictures/Screenshots/"
file="Screenshot_${time}_${RANDOM}.png"

# notify and view screenshot
notify_cmd_shot="notify-send -h string:x-canonical-private-synchronous:sys-notify-shot -u low -i ${iDIR}/picture.png"
notify_view() {
  "$notify_cmd_shot" "Copied to clipboard."
  # paplay sound disabled on NixOS
  # paplay /run/current-system/sw/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
  viewnior "$dir/$file"
  if [[ -e "$dir/$file" ]]; then
    "$notify_cmd_shot" "Screenshot Saved."
  else
    "$notify_cmd_shot" "Screenshot Deleted."
  fi
}

# countdown
countdown() {
  for sec in "$(seq "$1" -1 1)"; do
    notify-send -h string:x-canonical-private-synchronous:sys-notify-count -t 1000 -i "$iDIR"/timer.png "Taking shot in : $sec"
    sleep 1
  done
}

# take shots
shotnow() {
  cd "$dir" && sleep 0.5 && grim - | tee "$file" | wl-copy
  notify_view
}

shot5() {
  countdown '5'
  sleep 1 && cd "$dir" && grim - | tee "$file" | wl-copy
  notify_view
}

shot10() {
  countdown '10'
  sleep 1 && cd "$dir" && grim - | tee "$file" | wl-copy
  notify_view
}

shotwin() {
  w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
  w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
  cd "$dir" && grim -g "$w_pos $w_size" - | tee "$file" | wl-copy
  notify_view
}

shotarea() {
  # Ensure your variables are correctly set before this function is called
  # dir="..."
  # file="..."
  # background="..." (e.g., "#282a36")
  # accent="..." (e.g., "#ff79c6")

  # First, capture the geometry using slurp
  local geometry
  geometry=$(slurp -b "${background:1}CC" -c "${accent:1}ff" -s "${accent:1}0D" -w 2)

  # Check if slurp returned any geometry (e.g., user didn't cancel with Esc)
  if [ "$geometry" = "" ]; then
    echo "Screenshot cancelled or failed to select region."
    return 1
  fi

  # This give the Wayland compositor a moment to clear the slurp overly.
  sleep 1

  # Now perform the screenshot, tee to file, and copy to clipboard
  cd "$dir" && grim -g "$geometry" - | tee "$file" | wl-copy

  # If the sleep was intended to be after the screenshot and copy operation
  sleep 0.3
  notify_view # Assuming this is your notification function
}

if [[ ! -d "$dir" ]]; then
  mkdir -p "$dir"
fi

if [[ "$1" == "--now" ]]; then
  shotnow
elif [[ "$1" == "--in5" ]]; then
  shot5
elif [[ "$1" == "--in10" ]]; then
  shot10
elif [[ "$1" == "--win" ]]; then
  shotwin
elif [[ "$1" == "--area" ]]; then
  shotarea
else
  echo -e "Available Options : --now --in5 --in10 --win --area"
fi

exit 0
