#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/sinh/Pictures/Wallpapers/wallhaven-k7jgp7-3782x2521.jpeg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
