{
  lib,
  config,
  pkgs,
  namespace,
  inputs,
  ...
}:
let
  inherit (inputs.home-manager.lib) hm;
in
with lib;
let
  cfg = config.${namespace}.wm.hyprland;

  # Nix-interpolated values for scripts (use "auto" to indicate runtime detection)
  primaryMonitor = if cfg.monitors.primary != null then cfg.monitors.primary else "auto";
  primaryResolution =
    if cfg.monitors.primaryResolution != null then cfg.monitors.primaryResolution else "auto";
  externalResolution =
    if cfg.monitors.externalResolution != null then cfg.monitors.externalResolution else "auto";
  inherit (cfg.monitors) externalPosition refreshRate;
  inherit (cfg.workspaces) distribution;
  inherit (cfg.keybindings) generateFKeys;

  # Generated script: generate_workspace_config
  generateWorkspaceConfigScript = ''
        #!/usr/bin/env bash
        # Auto-generated by Nix - do not edit manually
        # Priority: user config file > Nix config > auto-detect

        CONFIG_FILE="$HOME/.config/hypr/workspaces.conf"
        VARS_FILE="$HOME/.config/hypr/monitor-vars.conf"
        LOG_FILE="$HOME/.config/hypr/workspace-gen.log"

        log() {
          echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
        }

        # Nix-interpolated values (second priority, used if vars file not set)
        NIX_PRIMARY_MONITOR="${primaryMonitor}"
        NIX_PRIMARY_RESOLUTION="${primaryResolution}"
        NIX_EXTERNAL_RESOLUTION="${externalResolution}"
        EXTERNAL_POSITION="${externalPosition}"
        REFRESH_RATE="${refreshRate}"
        DISTRIBUTION="${distribution}"
        GENERATE_FKEYS=${if generateFKeys then "true" else "false"}

        # Load user config file if exists (highest priority)
        if [ -f "$VARS_FILE" ]; then
          source "$VARS_FILE"
          log "INFO: Loaded user config from $VARS_FILE"
        fi

        # Runtime monitor detection
        if ! command -v hyprctl &>/dev/null; then
          log "ERROR: hyprctl not found, skipping workspace generation"
          exit 0
        fi

        MONITOR_JSON=$(hyprctl monitors -j 2>/dev/null)
        if [ -z "$MONITOR_JSON" ]; then
          log "ERROR: No monitors detected"
          exit 1
        fi

        MONITORS=$(echo "$MONITOR_JSON" | jq -r '.[].name' 2>/dev/null)

        # Resolve PRIMARY_MONITOR: user config > Nix config > auto-detect
        if [ -n "''${VAR_PRIMARY_MONITOR:-}" ]; then
          PRIMARY_MONITOR="$VAR_PRIMARY_MONITOR"
          log "INFO: Using user config primary monitor: $PRIMARY_MONITOR"
        elif [ "$NIX_PRIMARY_MONITOR" != "auto" ]; then
          PRIMARY_MONITOR="$NIX_PRIMARY_MONITOR"
          log "INFO: Using Nix config primary monitor: $PRIMARY_MONITOR"
        else
          PRIMARY_MONITOR=$(echo "$MONITORS" | head -1)
          log "INFO: Auto-detected primary monitor: $PRIMARY_MONITOR"
        fi

        # Resolve PRIMARY_RESOLUTION: user config > Nix config > auto-detect
        if [ -n "''${VAR_PRIMARY_RESOLUTION:-}" ]; then
          PRIMARY_RESOLUTION="$VAR_PRIMARY_RESOLUTION"
          PRIMARY_WIDTH=$(echo "$PRIMARY_RESOLUTION" | cut -d'x' -f1)
          PRIMARY_HEIGHT=$(echo "$PRIMARY_RESOLUTION" | cut -d'x' -f2)
          log "INFO: Using user config primary resolution: $PRIMARY_RESOLUTION"
        elif [ "$NIX_PRIMARY_RESOLUTION" != "auto" ]; then
          PRIMARY_RESOLUTION="$NIX_PRIMARY_RESOLUTION"
          PRIMARY_WIDTH=$(echo "$PRIMARY_RESOLUTION" | cut -d'x' -f1)
          PRIMARY_HEIGHT=$(echo "$PRIMARY_RESOLUTION" | cut -d'x' -f2)
          log "INFO: Using Nix config primary resolution: $PRIMARY_RESOLUTION"
        else
          PRIMARY_WIDTH=$(echo "$MONITOR_JSON" | jq -r ".[] | select(.name == \"$PRIMARY_MONITOR\") | .width")
          PRIMARY_HEIGHT=$(echo "$MONITOR_JSON" | jq -r ".[] | select(.name == \"$PRIMARY_MONITOR\") | .height")
          PRIMARY_RESOLUTION="''${PRIMARY_WIDTH}x''${PRIMARY_HEIGHT}"
          log "INFO: Auto-detected primary resolution: $PRIMARY_RESOLUTION"
        fi

        EXTERNAL_MONITOR=$(echo "$MONITORS" | grep -v "$PRIMARY_MONITOR" | head -1)

        # Resolve EXTERNAL_RESOLUTION: user config > Nix config > auto-detect
        if [ -n "$EXTERNAL_MONITOR" ]; then
          if [ -n "''${VAR_EXTERNAL_RESOLUTION:-}" ]; then
            EXTERNAL_RESOLUTION="$VAR_EXTERNAL_RESOLUTION"
            EXTERNAL_WIDTH=$(echo "$EXTERNAL_RESOLUTION" | cut -d'x' -f1)
            EXTERNAL_HEIGHT=$(echo "$EXTERNAL_RESOLUTION" | cut -d'x' -f2)
            log "INFO: Using user config external resolution: $EXTERNAL_RESOLUTION"
          elif [ "$NIX_EXTERNAL_RESOLUTION" != "auto" ]; then
            EXTERNAL_RESOLUTION="$NIX_EXTERNAL_RESOLUTION"
            EXTERNAL_WIDTH=$(echo "$EXTERNAL_RESOLUTION" | cut -d'x' -f1)
            EXTERNAL_HEIGHT=$(echo "$EXTERNAL_RESOLUTION" | cut -d'x' -f2)
            log "INFO: Using Nix config external resolution: $EXTERNAL_RESOLUTION"
          else
            EXTERNAL_WIDTH=$(echo "$MONITOR_JSON" | jq -r ".[] | select(.name == \"$EXTERNAL_MONITOR\") | .width")
            EXTERNAL_HEIGHT=$(echo "$MONITOR_JSON" | jq -r ".[] | select(.name == \"$EXTERNAL_MONITOR\") | .height")
            EXTERNAL_RESOLUTION="''${EXTERNAL_WIDTH}x''${EXTERNAL_HEIGHT}"
            log "INFO: Auto-detected external resolution: $EXTERNAL_RESOLUTION"
          fi
        fi

        log "INFO: Primary: $PRIMARY_MONITOR ($PRIMARY_RESOLUTION), External: ''${EXTERNAL_MONITOR:-none} (''${EXTERNAL_RESOLUTION:-n/a})"

        # Calculate external monitor position based on primary resolution
        get_external_position() {
          case "$EXTERNAL_POSITION" in
            left)  echo "-''${EXTERNAL_WIDTH}x0" ;;
            right) echo "''${PRIMARY_WIDTH}x0" ;;
            above) echo "0x-''${EXTERNAL_HEIGHT}" ;;
            below) echo "0x''${PRIMARY_HEIGHT}" ;;
            *)     echo "auto" ;;
          esac
        }

        # Determine LEFT and RIGHT monitors based on external position
        # Left monitor gets: 1-5, 11-15
        # Right monitor gets: 6-10, 16-20
        if [ -n "$EXTERNAL_MONITOR" ]; then
          case "$EXTERNAL_POSITION" in
            left)
              LEFT_MONITOR="$EXTERNAL_MONITOR"
              RIGHT_MONITOR="$PRIMARY_MONITOR"
              ;;
            right)
              LEFT_MONITOR="$PRIMARY_MONITOR"
              RIGHT_MONITOR="$EXTERNAL_MONITOR"
              ;;
            *)
              # For above/below, treat primary as left
              LEFT_MONITOR="$PRIMARY_MONITOR"
              RIGHT_MONITOR="$EXTERNAL_MONITOR"
              ;;
          esac
          log "INFO: Position layout - Left: $LEFT_MONITOR, Right: $RIGHT_MONITOR"
        fi

        # Generate workspace configuration
        cat >"$CONFIG_FILE" <<EOF
    # Auto-generated workspace configuration
    # Generated on: $(date)
    # Primary: $PRIMARY_MONITOR ($PRIMARY_RESOLUTION), External: ''${EXTERNAL_MONITOR:-none}
    # Distribution: $DISTRIBUTION, Position: $EXTERNAL_POSITION

    # Monitor setup
    monitor = $PRIMARY_MONITOR,preferred,0x0,1
    EOF

        if [ -n "$EXTERNAL_MONITOR" ]; then
          EXT_POS=$(get_external_position)
          cat >>"$CONFIG_FILE" <<EOF
    monitor = $EXTERNAL_MONITOR,$REFRESH_RATE,$EXT_POS,1
    EOF

          # Dual monitor workspace assignment based on distribution strategy
          if [ "$DISTRIBUTION" = "split" ]; then
            # Split by position: Left gets 1-5, 11-15; Right gets 6-10, 16-20
            cat >>"$CONFIG_FILE" <<EOF

    # Dual monitor workspace assignment (split by position)
    # Left monitor ($LEFT_MONITOR): workspaces 1-5, 11-15
    workspace = 1, monitor:$LEFT_MONITOR, persistent:true, default:true
    workspace = 2, monitor:$LEFT_MONITOR, persistent:true
    workspace = 3, monitor:$LEFT_MONITOR, persistent:true
    workspace = 4, monitor:$LEFT_MONITOR, persistent:true
    workspace = 5, monitor:$LEFT_MONITOR, persistent:true
    workspace = 11, monitor:$LEFT_MONITOR, persistent:true
    workspace = 12, monitor:$LEFT_MONITOR, persistent:true
    workspace = 13, monitor:$LEFT_MONITOR, persistent:true
    workspace = 14, monitor:$LEFT_MONITOR, persistent:true
    workspace = 15, monitor:$LEFT_MONITOR, persistent:true

    # Right monitor ($RIGHT_MONITOR): workspaces 6-10, 16-20
    workspace = 6, monitor:$RIGHT_MONITOR, persistent:true, default:true
    workspace = 7, monitor:$RIGHT_MONITOR, persistent:true
    workspace = 8, monitor:$RIGHT_MONITOR, persistent:true
    workspace = 9, monitor:$RIGHT_MONITOR, persistent:true
    workspace = 10, monitor:$RIGHT_MONITOR, persistent:true
    workspace = 16, monitor:$RIGHT_MONITOR, persistent:true
    workspace = 17, monitor:$RIGHT_MONITOR, persistent:true
    workspace = 18, monitor:$RIGHT_MONITOR, persistent:true
    workspace = 19, monitor:$RIGHT_MONITOR, persistent:true
    workspace = 20, monitor:$RIGHT_MONITOR, persistent:true
    EOF
          else
            # primary-all: Primary gets 1-10; External gets 11-20
            cat >>"$CONFIG_FILE" <<EOF

    # Dual monitor workspace assignment (primary-all distribution)
    # Primary monitor ($PRIMARY_MONITOR): workspaces 1-10
    workspace = 1, monitor:$PRIMARY_MONITOR, persistent:true, default:true
    workspace = 2, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 3, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 4, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 5, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 6, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 7, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 8, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 9, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 10, monitor:$PRIMARY_MONITOR, persistent:true

    # External monitor ($EXTERNAL_MONITOR): workspaces 11-20
    workspace = 11, monitor:$EXTERNAL_MONITOR, persistent:true, default:true
    workspace = 12, monitor:$EXTERNAL_MONITOR, persistent:true
    workspace = 13, monitor:$EXTERNAL_MONITOR, persistent:true
    workspace = 14, monitor:$EXTERNAL_MONITOR, persistent:true
    workspace = 15, monitor:$EXTERNAL_MONITOR, persistent:true
    workspace = 16, monitor:$EXTERNAL_MONITOR, persistent:true
    workspace = 17, monitor:$EXTERNAL_MONITOR, persistent:true
    workspace = 18, monitor:$EXTERNAL_MONITOR, persistent:true
    workspace = 19, monitor:$EXTERNAL_MONITOR, persistent:true
    workspace = 20, monitor:$EXTERNAL_MONITOR, persistent:true
    EOF
          fi

          # Generate F-key bindings for workspaces 11-20
          if [ "$GENERATE_FKEYS" = "true" ]; then
            cat >>"$CONFIG_FILE" <<EOFKEYS

    # F-key bindings for workspaces 11-20
    bind = SUPER, F1, workspace, 11
    bind = SUPER, F2, workspace, 12
    bind = SUPER, F3, workspace, 13
    bind = SUPER, F4, workspace, 14
    bind = SUPER, F5, workspace, 15
    bind = SUPER, F6, workspace, 16
    bind = SUPER, F7, workspace, 17
    bind = SUPER, F8, workspace, 18
    bind = SUPER, F9, workspace, 19
    bind = SUPER, F10, workspace, 20

    bind = SUPER_SHIFT, F1, movetoworkspace, 11
    bind = SUPER_SHIFT, F2, movetoworkspace, 12
    bind = SUPER_SHIFT, F3, movetoworkspace, 13
    bind = SUPER_SHIFT, F4, movetoworkspace, 14
    bind = SUPER_SHIFT, F5, movetoworkspace, 15
    bind = SUPER_SHIFT, F6, movetoworkspace, 16
    bind = SUPER_SHIFT, F7, movetoworkspace, 17
    bind = SUPER_SHIFT, F8, movetoworkspace, 18
    bind = SUPER_SHIFT, F9, movetoworkspace, 19
    bind = SUPER_SHIFT, F10, movetoworkspace, 20
    EOFKEYS
          fi
        else
          # Single monitor: all workspaces on primary
          cat >>"$CONFIG_FILE" <<EOFSINGLE

    # Single monitor workspace assignment
    workspace = 1, monitor:$PRIMARY_MONITOR, persistent:true, default:true
    workspace = 2, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 3, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 4, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 5, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 6, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 7, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 8, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 9, monitor:$PRIMARY_MONITOR, persistent:true
    workspace = 10, monitor:$PRIMARY_MONITOR, persistent:true
    EOFSINGLE
        fi

        log "INFO: Workspace configuration generated: $CONFIG_FILE"
        echo "Workspace configuration generated: $CONFIG_FILE"

        # Reload Hyprland config if running
        if pgrep -x "Hyprland" >/dev/null; then
          hyprctl reload
          log "INFO: Hyprland config reloaded"
        fi
  '';

  # Generated script: monitor_watcher
  monitorWatcherScript = ''
    #!/usr/bin/env bash
    # Auto-generated by Nix - do not edit manually

    SCRIPT_DIR="$HOME/.config/hypr/scripts"

    # Run initial workspace generation
    "$SCRIPT_DIR/generate_workspace_config"

    handle() {
      case $1 in
        monitoradded*|monitorremoved*)
          echo "Monitor change detected: $1"
          sleep 1
          "$SCRIPT_DIR/generate_workspace_config"
          ;;
      esac
    }

    socat -U - UNIX-CONNECT:"$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do
      handle "$line"
    done
  '';

  # Filter to exclude scripts and files we're generating at runtime
  hyprConfigFilter =
    path: _:
    let
      baseName = baseNameOf path;
    in
    !(
      baseName == "generate_workspace_config"
      || baseName == "monitor_watcher"
      || baseName == "workspaces.conf"
    );
in
{
  options.${namespace}.wm.hyprland = {
    enable = mkEnableOption "Hyprland config using hm";

    monitors = {
      primary = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Primary monitor name (e.g., eDP-1, DP-1). Auto-detected if null.";
        example = "eDP-1";
      };

      primaryResolution = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Primary monitor resolution (WIDTHxHEIGHT). Auto-detected at runtime if null.";
        example = "3840x2400";
      };

      externalResolution = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "External monitor resolution (WIDTHxHEIGHT). Auto-detected at runtime if null.";
        example = "2560x1440";
      };

      externalPosition = mkOption {
        type = types.enum [
          "left"
          "right"
          "above"
          "below"
        ];
        default = "right";
        description = "Position of external monitors relative to primary.";
      };

      refreshRate = mkOption {
        type = types.enum [
          "preferred"
          "highrr"
          "highres"
        ];
        default = "preferred";
        description = "Refresh rate mode for external monitors.";
      };
    };

    workspaces = {
      distribution = mkOption {
        type = types.enum [
          "split"
          "primary-all"
        ];
        default = "split";
        description = ''
          Workspace distribution strategy:
          - split: First half on primary, second half on external (1-5 primary, 6-10 external)
          - primary-all: All base workspaces (1-10) on primary, extended (11-20) on external
        '';
      };
    };

    keybindings = {
      generateFKeys = mkOption {
        type = types.bool;
        default = true;
        description = "Generate F1-F10 bindings for workspaces 11-20.";
      };
    };
  };

  config = mkIf cfg.enable {
    home = {
      packages = with pkgs; [
        jq
        socat
      ];

      file = {
        # Copy static config files, excluding generated scripts
        ".config/hypr" = {
          source = lib.cleanSourceWith {
            src = ./hypr_config;
            filter = hyprConfigFilter;
          };
          recursive = true;
        };

        # Generated scripts
        ".config/hypr/scripts/generate_workspace_config" = {
          executable = true;
          text = generateWorkspaceConfigScript;
        };

        ".config/hypr/scripts/monitor_watcher" = {
          executable = true;
          text = monitorWatcherScript;
        };
      };

      # Generate initial workspaces.conf during home-manager activation
      # This creates a real file (not symlink) that can be overwritten at runtime
      activation.generateHyprlandWorkspaces = hm.dag.entryAfter [ "writeBoundary" ] ''
              CONFIG_DIR="$HOME/.config/hypr"
              CONFIG_FILE="$CONFIG_DIR/workspaces.conf"

              # Only generate if file doesn't exist (preserve runtime changes)
              if [ ! -f "$CONFIG_FILE" ]; then
                mkdir -p "$CONFIG_DIR"
                cat > "$CONFIG_FILE" << 'EOFWS'
        # Placeholder workspace configuration
        # Will be regenerated at Hyprland startup by monitor_watcher

        # Fallback monitor setup (auto-detected at runtime)
        monitor = ,preferred,auto,1

        # Default persistent workspaces
        workspace = 1, persistent:true, default:true
        workspace = 2, persistent:true
        workspace = 3, persistent:true
        workspace = 4, persistent:true
        workspace = 5, persistent:true
        workspace = 6, persistent:true
        workspace = 7, persistent:true
        workspace = 8, persistent:true
        workspace = 9, persistent:true
        workspace = 10, persistent:true
        EOFWS
                echo "Generated initial workspaces.conf placeholder"
              fi
      '';
    };
  };
}
